### ISSUE TITLE
FAQ - big data report

### ISSUE THREAD

**Issue by shortthefomo** [hmatejx/xrapid_search#3]
Never used google big data, what does it cost to run your report? 
You ever thought of porting that part to another free service?

thx.

**Comment by hmatejx** [comment]
It does not cost anything as long as you stay under the limit.

I have not considered using a free service as the raw data is not easily available elsewhere.

My queries are relying on the excellent work by @WietseWind: https://github.com/WietseWind/fetch-xrpl-transactions who already populates the xrpledgerdata.fullhistory data set in BigQuery, which I use here.

**Comment by hmatejx** [comment]
I will close this issue, but if anyone would like to take this up, it is fine for me, just be aware it would be a significant exercise.
